#!/bin/bash                                                                                     
#       author: eleAche                                               
#       title: CUERVO  1.0                              "cria cuervos y sacaran tus             
#                                                        ojos de sus cuencas." -cancerbero      
#                                                .________________________________________.
mkdir .TheMadafackerDeepWeb ; #          [  make
cp $0 .TheMadafackerDeepWeb/; #             work
cd .TheMadafackerDeepWeb; #                 space. | Los modales hacen al hombre... ]

# LEE PARAMETROS
if [[ $# -eq 0 ]]; then
    Eyes=('facebook ' 'google ' 'amazon ' 'microsoft ' 'apple ' 'yahoo ' 'dropbox');
fi
PRIMERO=1
while [ -n "$1" ]; do        
        if [ $PRIMERO -eq 1 ]; then
                Eyes="$1"
        else
                Eyes="$Eyes $1"
        fi
        shift
done
S__='pacman -Ss ' # arch distro linux 
S_='apt-cache show '
echo -e " ${graCol} esta es la cantidad de herramientas que vamos a tomar ${EndCol}${yelCol}prestadas${EndCol}${graCol}... ${EndCol}"

# RECOPILAR DATOS
for (( C=0; C<=5; C++ ));do
        ${S__}${Eyes[C]} > .singleEye[$C]
        cat -n .singleEye[$C] > .Numeracion[$C]
        Contador={ tail -n 1 .Numeracion[$C] | awk 'BEGIN{ORS= " "}{print $1}' 
        echo -e "${bluCol}~  $Contador ~ ${Eyes[C]}${EndCol} "
        cat .singleEye[$C] > .Listalib[$C];
done
echo -e "\n\n ${graCol}  es mucho poder sr. wayne!!!!\n\n\n${EndCol}"

# IMPRIME TITULO:DESCRIPCION DE RESULTADOS
echo -e "${graCol} ... quieres que imprima lo que tomaremos prestado? ( Y / N ) ${EndCol}"
read imprimir
if [ $imprimir="Y" ] ;then
        for (( Boiler=0; Boiler<=4; Boiler++ ));do
        cat .Listalib[$Boiler]
        done
else    
        exit 1
fi

# IMPRIME LOCALIZACION DE RESULTADOS
echo -e "${graCol}ahora quieres que localize todos estos aportes? ( Y / N ) ${EndCol}" ;
read mostrar;
echo -e "${redCol} "
if [ $mostrar="Y" ];then
        for (( homeless=0; homeless<=4; homeless++ ));do
        cat .Listalib[$homeless] | awk 'BEGIN{ORS= " "}{print $1}' > solokeywords[$homeless]
        ${S_}$solokeywords[$homeless] |grep Homepage |sort -u
        done
else 
        exit 1
fi

# EJECUCION EXITOSA
echo -e "${EndCol} "
echo -e "${bluCol} [+] Correcto...  ${EndCol}"
cd ..;
rm -r .TheMadafackerDeepWeb > /dev/null; # travesura realizada
exit 1
