#!/bin/bash                                                                                     
#       author: eleAche                                               
#       title: CUERVO  1.0                              "cria cuervos y sacaran tus             
#                                                        ojos de sus cuencas." -cancerbero      
#                                                .________________________________________.